name: Publish to surge on push

on: push

jobs:
  publish-job:
    name: Publish to surge
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to phil.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'phil.surge.sh'
          project: 'dist'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
